version: "3.7"
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: letmein

  ipfs:
    image: ipfs/go-ipfs:v0.4.23
    ports:
      - "5001:5001"

  ganache:
    image: trufflesuite/ganache-cli:v6.9.1
    ports:
      - "8545:8545"

  graph-node:
    image: graphprotocol/graph-node:v0.19.0
    depends_on:
      - ipfs
      - postgres
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8020:8020"
      - "8030:8030"
      - "8040:8040"
    environment:
      postgres_host: "postgres"
      postgres_user: postgres
      postgres_pass: letmein
      postgres_db: postgres
      ipfs: "ipfs:5001"
      ethereum: "development:http://ganache:8545"
      GRAPH_LOG: debug
