version: '3.7'
services:
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: letmein
    volumes:
      - pdata:/var/lib/postgresql/data

  ipfs:
    image: ipfs/kubo:latest
    ports:
      - '5001:5001'

  graph-node:
    image: graphprotocol/graph-node:v0.25.0
    depends_on:
      - ipfs
      - postgres
    ports:
      - '8000:8000'
      - '8001:8001'
      - '8020:8020'
      - '8030:8030'
      - '8040:8040'
    environment:
      postgres_host: 'postgres'
      postgres_user: postgres
      postgres_pass: letmein
      postgres_db: postgres
      ipfs: 'ipfs:5001'
      ethereum: "mainnet:http://host.docker.internal:8545"
      GRAPH_LOG: debug
    extra_hosts:
        - "host.docker.internal:host-gateway"

volumes:
  pdata:
    driver: local
