version: '3.7'
services:
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: letmein

  ipfs:
    image: ipfs/go-ipfs:v0.4.23
    ports:
      - '5001:5001'

  graph-node:
    image: graphprotocol/graph-node:v0.25.0
    depends_on:
      - ipfs
      - postgres
    ports:
      - '8000:8000'
      - '8001:8001'
      - '8020:8020'
      - '8030:8030'
      - '8040:8040'
    environment:
      postgres_host: 'postgres'
      postgres_user: postgres
      postgres_pass: letmein
      postgres_db: postgres
      ipfs: 'ipfs:5001'
      ethereum: 'mainnet:http://hardhat:8545'
      GRAPH_LOG: debug


  hardhat:
    image: hardhat_local
    build:
      context: ./hardhat
      dockerfile: Dockerfile
    ports:
      - '8545:8545'
    environment:
      PRIVATE_KEY: c5e8f61d1ab959b397eecc0a37a6517b8e67a0e7cf1f4bce5591f3ed80199122
    volumes:
      - ./hardhat/data/artifacts:/phuture-contracts/artifacts
      - ./hardhat/data/typechain:/phuture-contracts/typechain
    command: npx hardhat node --fork https://eth-mainnet.alchemyapi.io/v2/ljuhEKChZyTo674bWzx7mq5cbc4gT3a5


  hardhat-deploy:
    image: hardhat_local
    depends_on:
      - hardhat
    environment:
      PRIVATE_KEY: c5e8f61d1ab959b397eecc0a37a6517b8e67a0e7cf1f4bce5591f3ed80199122
      GAS_PRICE_GWEI: 149
      SKIP_CONFIRMATION: 'true'
      FORK: 'true'
      MAINNET_HTTPS_URL: https://empty.com
    volumes:
      - ./hardhat/data/artifacts:/phuture-contracts/artifacts
      - ./hardhat/data/typechain:/phuture-contracts/typechain
      - ./hardhat/data/mvp-output:/phuture-contracts/mvp-output
      - ./hardhat/data/.npm:/root/.npm
    command: npm run deploy:local

