// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import {
  Address,
  DataSourceTemplate,
  DataSourceContext
} from "@graphprotocol/graph-ts";

export class Asset extends DataSourceTemplate {
  static create(address: Address): void {
    DataSourceTemplate.create("Asset", [address.toHex()]);
  }

  static createWithContext(address: Address, context: DataSourceContext): void {
    DataSourceTemplate.createWithContext("Asset", [address.toHex()], context);
  }
}

export class StaticIndex extends DataSourceTemplate {
  static create(address: Address): void {
    DataSourceTemplate.create("StaticIndex", [address.toHex()]);
  }

  static createWithContext(address: Address, context: DataSourceContext): void {
    DataSourceTemplate.createWithContext(
      "StaticIndex",
      [address.toHex()],
      context
    );
  }
}

export class UniswapPair extends DataSourceTemplate {
  static create(address: Address): void {
    DataSourceTemplate.create("UniswapPair", [address.toHex()]);
  }

  static createWithContext(address: Address, context: DataSourceContext): void {
    DataSourceTemplate.createWithContext(
      "UniswapPair",
      [address.toHex()],
      context
    );
  }
}
