// This data generated by after deployment of the set of contracts, must be updated after each upgrade as is.
let data = {
  "Base":"0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48",
  "WETH":"0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2",
  "FeePool":"0xec236d0f82e005e40e98db8c54c3ce248c3ca7c6",
  "Registry":"0xd1a602a1a1821cd06de6c282eedc27b8bfc640b2",
  "ManagedIndexFactory":"0x031a7465da71b80ab136a129939aba809fd04326",
  "ReweightingCredit":"0x9e9ad863adf25c5df5d81415ad38b405142be76a",
  "TopNMarketCapCategories":"0xe6849d3d61c8f14b9bd9f30dde8503ff0d16520e",
  "TopNMarketCapIndexFactory":"0xa910425c59484a4573e8323c19a78ff4433156ec",
  "ManagedVTokenFactory":"0xe02058acc648d57688173b98585545cc17cb5695",
  "DynamicVTokenFactory":"0xef792b67364d9edbe3c5c729501e1d9623a2ef61",
  "Orderer":"0xb2b1b2518419bc847ad750981e9fd67b8e1f937f",
  "UniswapV2Factory":"0x5c69bee701ef814a2b6a3edd4b1652cb9cc5aa6f",

  "UniswapV2FactoryBlockNumber":14228182,"SushiV2FactoryBlockNumber":14228182,"RegistryBlockNumber":14229592,"OrdererBlockNumber":14229625,"ManagedIndexFactoryBlockNumber":14229640,"ManagedVTokenFactoryBlockNumber":14229631,"DynamicVTokenFactoryBlockNumber":14229632,"TopNMarketCapIndexFactoryBlockNumber":14229651,

  SushiswapV2Factory: '0xc35dadb65012ec5796536bd9864ed8773abc74c4',

  TrackedIndexFactory: '0x3a6fef3a4bb4ec3bce7fa7f2c53cf0f82c49fe36',
  TrackedIndexFactoryBlockNumber: 14228182,

  UniswapV2Router: "0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D",
  UniswapV2RouterBlockNumber: 14228182,

  SushiswapV2Router: "0xd9e1cE17f2641f24aE83637ab66a2cca9C378B9F",
  SushiswapV2RouterBlockNumber: 14228182,

  FeePoolBlockNumber: 14228182,
  RebalancingCredit: '0xea51c983a2209d16a597d219d472204a9666972c',
};

data['emissionControllerContractAddress'] = '0xc8b08ada13359b01e6e42d8f48159181a299f42b';

data['swapFactories'] = [
  {
    "name": "SushiswapFactory",
    "factoryAddress": data.SushiswapV2Factory,
    "startBlock": data.SushiV2FactoryBlockNumber
  },
  {
    'name': 'UniswapFactory',
    'factoryAddress': data.UniswapV2Factory,
    'startBlock': data.UniswapV2FactoryBlockNumber,
  },
];

data['network'] = 'mainnet';

let pairs = [
  {
    'name': 'USDC',
    'address': '0x91b843dcb637323db7728e59995cfa02abb5111d',
    'aggregatorAddress': '0x4E94A9d221CE5CFE90B976600DaAAc639f936b66',
    'block': 9645935,
    'decimals': 8,
  },
  {
    'name': 'WETH',
    'address': '0xc778417e063141139fce010982780140aa0cd5ab',
    'aggregatorAddress': '0x8FAcAE210C796Bcac7afE147b622FFc1064629f6',
    'block': 9645935,
    'decimals': 8,
  },
  {
    'name': 'LINK',
    'address': '0xc4188db6106e0c6a5584cbb349fcd0d1e7d4e3b4',
    'aggregatorAddress': '0x63Da64115bb2dF82dDC9Bb4F98F0Cce652c1581a',
    'block': 9645935,
    'decimals': 8,
  },
  {
    'name': 'DAI',
    'address': '0xaad94292e6ff68ba21173e048643fcbf26040dfd',
    'aggregatorAddress': '0x0720C40EDf5e88dFA8e8cd015296e4F3eDE5679A',
    'block': 9645935,
    'decimals': 8,
  },
  {
    'name': 'WBTC',
    'address': '0x19b61b29fccce4fc1202051c8265cb2eff5ba110',
    'aggregatorAddress': '0xf03511fa3A4B816a400aE2a7D14b1892E14d18d4',
    'block': 9645935,
    'decimals': 8,
  },
  {
    'name': 'USDT',
    'address': '0xe9ac343f0de7f14b8774a90de364f2b44db7e460',
    'aggregatorAddress': '0x4E94A9d221CE5CFE90B976600DaAAc639f936b66',
    'block': 9645935,
    'decimals': 8,
  },
  {
    'name': 'UNI',
    'address': '0xbf483237e2b8e29360828022ee22eddd59b9becf',
    'aggregatorAddress': '0xECf6936AD6030A1Aa4f2055Df44149B7846628F7',
    'block': 9645935,
    'decimals': 8,
  },
  {
    'name': 'COMP',
    'address': '0x682626b232489b494be74940fbed5047792da5fb',
    'aggregatorAddress': '0x2217fE4CE584800131cEFC440B9f2937E50ebf1a',
    'block': 9645935,
    'decimals': 8,
  },
  {
    'name': 'SUSHI',
    'address': '0x0b5b4cd52a8e709c61f9cffd8cfb9b47b9bef2f3',
    'aggregatorAddress': '0xC4b4fAD3DC8C08DBa5d639A6e435f116b9282DB0',
    'block': 9645935,
    'decimals': 8,
  },
  {
    'name': 'KP3R',
    'address': '0x47cb1858e9a995581714cf04324f1d0151bcab5c',
    'aggregatorAddress': '0xad26BAb8AAB6514AC56f66ae0c1bb9afACCC1d0A',
    'block': 9645935,
    'decimals': 8,
  },
  {
    'name': 'MIR',
    'address': '0x30476217214716013698481e53b8980b517e0148',
    'aggregatorAddress': '0x24959556020AE5D39e5bAEC2bd6Bf12420C25aB5',
    'block': 9645935,
    'decimals': 8,
  },
  {
    'name': 'SNX',
    'address': '0xeee3c51505f033d12a9d2f24aa175c6f40ba5c9b',
    'aggregatorAddress': '0x24959556020AE5D39e5bAEC2bd6Bf12420C25aB5',
    'block': 9645935,
    'decimals': 8,
  },
  {
    'name': 'PHTR',
    'address': '0x7eace45c46182a70d9a208557250de8d201aa0b2',
    'aggregatorAddress': '0x24959556020AE5D39e5bAEC2bd6Bf12420C25aB5',
    'block': 9645935,
    'decimals': 8,
  },
  {
    'name': 'mTSLA',
    'address': '0x70498ef4182813507a8e7caae3fd56ea736774b9',
    'aggregatorAddress': '0x24959556020AE5D39e5bAEC2bd6Bf12420C25aB5',
    'block': 9645935,
    'decimals': 8,
  },
  {
    'name': 'mAMZN',
    'address': '0xd8f27968b5f1d9990038364df9417bde4b4bcc27',
    'aggregatorAddress': '0x24959556020AE5D39e5bAEC2bd6Bf12420C25aB5',
    'block': 9645935,
    'decimals': 8,
  },
  {
    'name': 'ZRX',
    'address': '0xa1f92487f5ff329b68f892b5ebcb0f46d8c4db10',
    'aggregatorAddress': '0x24959556020AE5D39e5bAEC2bd6Bf12420C25aB5',
    'block': 9645935,
    'decimals': 8,
  },
  {
    'name': 'AAVE',
    'address': '0x70cd094bfe26931fa9d1d1bf26ce4b00d62ebd59',
    'aggregatorAddress': '0x24959556020AE5D39e5bAEC2bd6Bf12420C25aB5',
    'block': 9645935,
    'decimals': 8,
  },
  {
    'name': 'mMSFT',
    'address': '0x8853bfbeeb6b044e5db96861d304da92ff655d55',
    'aggregatorAddress': '0x24959556020AE5D39e5bAEC2bd6Bf12420C25aB5',
    'block': 9645935,
    'decimals': 8,
  },
  {
    'name': 'mAAPL',
    'address': '0x3e55d2d54a60e398283fad37607cdc35a8740c5d',
    'aggregatorAddress': '0x24959556020AE5D39e5bAEC2bd6Bf12420C25aB5',
    'block': 9645935,
    'decimals': 8,
  },
  {
    'name': 'YFI',
    'address': '0xbd48ea3a33f80985a5a77a16ff7b0d3ec705b1ab',
    'aggregatorAddress': '0x24959556020AE5D39e5bAEC2bd6Bf12420C25aB5',
    'block': 9645935,
    'decimals': 8,
  },
];

module.exports = {
  data,
  pairs,
};
