// This data generated by after deployment of the set of contracts, must be updated after each upgrade as is.
let data = {
  FeePool: '0x267da4d6b0b6f806ab578513869288b428ffb3df',
  Base: '0xd6b0d9095d23882d63142c8ded37744e0436331b',
  PHTR: '0x0ca4e8cc4ec0b5717f21c594dd21a9e032953e45',
  WETH: '0xc778417e063141139fce010982780140aa0cd5ab',
  OraclePrice: '0x71bb23864d7b3b693f3dff3dfe855237bdf2934a',
  UniswapV2Factory: '0x5c69bee701ef814a2b6a3edd4b1652cb9cc5aa6f',
  Registry: '0xa9ae1de112ebdafde129090fe0c4fee8f6b7bc94',
  IndexRouter: '0x0c27455c1779ed36ee041ff0827fdd972ad7d956',
  RebalancingCredit: '0x5eea1a8d16705234af917ad47c665ec47bc0d064',
  StaticIndexFactory: '0xde09970ce9fac8ff20aa7a08d17fd6432c5bf1b1',
  TrackedIndexFactory: '0x3a6fef3a4bb4ec3bce7fa7f2c53cf0f82c49fe36',
  TopNMarketCapIndexFactory: '0x125767dea3558ae365f1c790d3b7818367f0bb51',
  TopNMarketCapCategories: '0xd2bb7ae624bc544ae1f7b9c6a7f3e85dd2cee9aa',
  SharedOwnershipCreator: '0xba5960340fc53d6abb6712f302be85dd02181eb4',
  vTokenFactory: '0xc5e67305e0f93a78f1345da38adfa257decdde14',
  assets: [
    '0xd6b0d9095d23882d63142c8ded37744e0436331b',
    '0x6ee933eb5e877d5c4885ae55fc208ee88293e896',
    '0xbca3aaf5d62bf8bebdce22cef21e2c7f24602124',
    '0x1ae73a643309a1caf38693ba9712abf4b85a0689',
    '0xff30b0d9c9a4d3e344aaf454ad879f99bc0d06b0',
    '0x3347a2346aa45571426b463727bef778b3bbb0df',
    '0xf0cda527cfc4e34a4c678a88e2ceb1cb688e7e31',
    '0x8c4f69eca35cbb9ba32832dafcb4e01b92c9301e',
    '0x66972f839657984bef52bc8670067d704adde3d6',
    '0x3f0dea029df5a4e05d26edab9e333cccd19eec15',
    '0xa2b0cab9759b3cd06d7e2ecfd0a6ee1084988c17',
    '0x6f4741760ec5491ca4f2b40d957fcb2b22ab6ba3',
    '0xe5d97e7739043eb887abf5daa6fd6f703e8707de'
  ],
  TestWETH: '0x6ee933eb5e877d5c4885ae55fc208ee88293e896',
  USDC: '0xd6b0d9095d23882d63142c8ded37744e0436331b',
  WBTC: '0xbca3aaf5d62bf8bebdce22cef21e2c7f24602124',
  UNI: '0x1ae73a643309a1caf38693ba9712abf4b85a0689',
  LINK: '0xff30b0d9c9a4d3e344aaf454ad879f99bc0d06b0',
  AAVE: '0x3347a2346aa45571426b463727bef778b3bbb0df',
  OHM: '0xf0cda527cfc4e34a4c678a88e2ceb1cb688e7e31',
  MKR: '0x8c4f69eca35cbb9ba32832dafcb4e01b92c9301e',
  SUSHI: '0x66972f839657984bef52bc8670067d704adde3d6',
  COMP: '0x3f0dea029df5a4e05d26edab9e333cccd19eec15',
  SNX: '0xa2b0cab9759b3cd06d7e2ecfd0a6ee1084988c17',
  YFI: '0x6f4741760ec5491ca4f2b40d957fcb2b22ab6ba3',
  CRV: '0xe5d97e7739043eb887abf5daa6fd6f703e8707de',
  CCI: '0x2cA0042d34D7770E9794E3A0D41D2e67F7F45c22',
  PDI: '0x198c9098681Ae2A380b2a7bE726B6B9728B12b87',

  StaticIndexFactoryBlockNumber: 9813093,
  RegistryBlockNumber: 9813080,
  StaticIndexFactoryRegistryBlockNumber: 9813080,
  vTokenFactoryBlockNumber: 9813080,
  FeePoolRegistryBlockNumber: 9813080,
  TrackedIndexFactoryBlockNumber: 9813080,
  TopNMarketCapIndexFactoryBlockNumber:9813102
};

data['network'] = 'rinkeby';

let pairs = [
  {
    "name": "USDC",
    "address": "0x91b843dcb637323db7728e59995cfa02abb5111d",
    "aggregatorAddress": "0x4E94A9d221CE5CFE90B976600DaAAc639f936b66",
    "block": 9645935,
    "decimals": 8
  },
  {
    "name": "WETH",
    "address": "0xc778417e063141139fce010982780140aa0cd5ab",
    "aggregatorAddress": "0x8FAcAE210C796Bcac7afE147b622FFc1064629f6",
    "block": 9645935,
    "decimals": 8
  },
  {
    "name": "LINK",
    "address": "0xc4188db6106e0c6a5584cbb349fcd0d1e7d4e3b4",
    "aggregatorAddress": "0x63Da64115bb2dF82dDC9Bb4F98F0Cce652c1581a",
    "block": 9645935,
    "decimals": 8
  },
  {
    "name": "DAI",
    "address": "0xaad94292e6ff68ba21173e048643fcbf26040dfd",
    "aggregatorAddress": "0x0720C40EDf5e88dFA8e8cd015296e4F3eDE5679A",
    "block": 9645935,
    "decimals": 8
  },
  {
    "name": "WBTC",
    "address": "0x19b61b29fccce4fc1202051c8265cb2eff5ba110",
    "aggregatorAddress": "0xf03511fa3A4B816a400aE2a7D14b1892E14d18d4",
    "block": 9645935,
    "decimals": 8
  },
  {
    "name": "USDT",
    "address": "0xe9ac343f0de7f14b8774a90de364f2b44db7e460",
    "aggregatorAddress": "0x4E94A9d221CE5CFE90B976600DaAAc639f936b66",
    "block": 9645935,
    "decimals": 8
  },
  {
    "name": "UNI",
    "address": "0xbf483237e2b8e29360828022ee22eddd59b9becf",
    "aggregatorAddress": "0xECf6936AD6030A1Aa4f2055Df44149B7846628F7",
    "block": 9645935,
    "decimals": 8
  },
  {
    "name": "COMP",
    "address": "0x682626b232489b494be74940fbed5047792da5fb",
    "aggregatorAddress": "0x2217fE4CE584800131cEFC440B9f2937E50ebf1a",
    "block": 9645935,
    "decimals": 8
  },
  {
    "name": "SUSHI",
    "address": "0x0b5b4cd52a8e709c61f9cffd8cfb9b47b9bef2f3",
    "aggregatorAddress": "0xC4b4fAD3DC8C08DBa5d639A6e435f116b9282DB0",
    "block": 9645935,
    "decimals": 8
  },
  {
    "name": "KP3R",
    "address": "0x47cb1858e9a995581714cf04324f1d0151bcab5c",
    "aggregatorAddress": "0xad26BAb8AAB6514AC56f66ae0c1bb9afACCC1d0A",
    "block": 9645935,
    "decimals": 8
  },
  {
    "name": "MIR",
    "address": "0x30476217214716013698481e53b8980b517e0148",
    "aggregatorAddress": "0x24959556020AE5D39e5bAEC2bd6Bf12420C25aB5",
    "block": 9645935,
    "decimals": 8
  },
  {
    "name": "SNX",
    "address": "0xeee3c51505f033d12a9d2f24aa175c6f40ba5c9b",
    "aggregatorAddress": "0x24959556020AE5D39e5bAEC2bd6Bf12420C25aB5",
    "block": 9645935,
    "decimals": 8
  },
  {
    "name": "PHTR",
    "address": "0x7eace45c46182a70d9a208557250de8d201aa0b2",
    "aggregatorAddress": "0x24959556020AE5D39e5bAEC2bd6Bf12420C25aB5",
    "block": 9645935,
    "decimals": 8
  },
  {
    "name": "mTSLA",
    "address": "0x70498ef4182813507a8e7caae3fd56ea736774b9",
    "aggregatorAddress": "0x24959556020AE5D39e5bAEC2bd6Bf12420C25aB5",
    "block": 9645935,
    "decimals": 8
  },
  {
    "name": "mAMZN",
    "address": "0xd8f27968b5f1d9990038364df9417bde4b4bcc27",
    "aggregatorAddress": "0x24959556020AE5D39e5bAEC2bd6Bf12420C25aB5",
    "block": 9645935,
    "decimals": 8
  },
  {
    "name": "ZRX",
    "address": "0xa1f92487f5ff329b68f892b5ebcb0f46d8c4db10",
    "aggregatorAddress": "0x24959556020AE5D39e5bAEC2bd6Bf12420C25aB5",
    "block": 9645935,
    "decimals": 8
  },
  {
    "name": "AAVE",
    "address": "0x70cd094bfe26931fa9d1d1bf26ce4b00d62ebd59",
    "aggregatorAddress": "0x24959556020AE5D39e5bAEC2bd6Bf12420C25aB5",
    "block": 9645935,
    "decimals": 8
  },
  {
    "name": "mMSFT",
    "address": "0x8853bfbeeb6b044e5db96861d304da92ff655d55",
    "aggregatorAddress": "0x24959556020AE5D39e5bAEC2bd6Bf12420C25aB5",
    "block": 9645935,
    "decimals": 8
  },
  {
    "name": "mAAPL",
    "address": "0x3e55d2d54a60e398283fad37607cdc35a8740c5d",
    "aggregatorAddress": "0x24959556020AE5D39e5bAEC2bd6Bf12420C25aB5",
    "block": 9645935,
    "decimals": 8
  },
  {
    "name": "YFI",
    "address": "0xbd48ea3a33f80985a5a77a16ff7b0d3ec705b1ab",
    "aggregatorAddress": "0x24959556020AE5D39e5bAEC2bd6Bf12420C25aB5",
    "block": 9645935,
    "decimals": 8
  }
];

module.exports = {
  data, pairs,
}