name: Test

on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
      - develop

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          path: './pathToRepo/'

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Build1
        run: cd ./pathToRepo/subgraphs/mvp && npm install --force && npm run codegen

      - name: Build2
        run: cd ./pathToRepo && cp -r node_modules/matchstick-as/ subgraphs/mvp/node_modules/

      - name: Build3
        run: cd ./pathToRepo/subgraphs/mvp && ln -s ../../node_modules/@graphprotocol/graph-cli/bin/graph .

      - name: Test
        run: cd ./pathToRepo/subgraphs/mvp && ./graph test
