name: Build

on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
      - develop
  pull_request:
    #temp    branches: [ develop ]

env:
  TMPDIR: /tmp/unzip

jobs:
  file_existence:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          path: './pathToRepo/'

      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "./pathToRepo/zip/mvp-output.zip"

      - name: File exists
        if: steps.check_files.outputs.files_exists == 'true'
        # Only runs if all of the files exists
        run: |
          unzip ./pathToRepo/zip/*.zip -d $TMPDIR
          for f in $TMPDIR/mvp-output/subgraph/abi/*.json; do bn=$(basename $f) && cat $f | jq | tee ./pathToRepo/subgraphs/abis/Phuture/$bn > /dev/null; done
          for f in $TMPDIR/mvp-output/subgraph/*.json; do bn=$(basename $f) && cat $f | jq | tee ./pathToRepo/subgraphs/mvp/config/$bn > /dev/null; done
          rm ./pathToRepo/zip/*.zip

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Build
        run: cd ./pathToRepo && npm install --force && npm run codegen

      # It should have a squashed commit before merging to develop
      - uses: EndBug/add-and-commit@v9
        with:
          message: 'Updated subgraphs files'
          add: '["./zip", "./subgraphs/abis", "./subgraphs/mvp/config"]'
          cwd: './pathToRepo/'
          default_author: github_actions
          committer_name: GitHub Actions
